# Generated by Django 4.2 on 2023-04-12 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TODOlist_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='order_num',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
